<?php
session_start();
unset($_SESSION["User_id"]);
unset($_SESSION["Username"]);
unset($_SESSION["Status"]);
unset($_SESSION['interest']);
unset($_SESSION['errors']);
unset($_SESSION['User_id']);
header("Location:login.php");
?>